spring.application.name=question-service

spring.data.mongodb.uri=mongodb+srv://vibhashanadev:08RUsV1DaSHgmWIn@springboot.0enwu.mongodb.net/
spring.data.mongodb.database=questions_db

server.port=5000